version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pixs6716_jogo
      - DB_USERNAME=pixs6716_jogo
      - DB_PASSWORD=9qj5uo88ekqp
    depends_on:
      - db
      - nginx
    #command: "bash -c 'composer install && php artisan migrate && php-fpm'"
    ports:
      - "9000:9000"

  db:
    image: "mysql:8.2"
    networks:
      - laravel-network
    environment:
      - MYSQL_ROOT_PASSWORD=9qj5uo88ekqp
      - MYSQL_DATABASE=pixs6716_jogo
      - MYSQL_USER=pixs6716_jogo
      - MYSQL_PASSWORD=9qj5uo88ekqp
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - laravel-network
    ports:
      - "8081:80"  # Mapeando a porta 7777 do host para a porta 80 do PHPMyAdmin
    depends_on:
      - db
      - nginx

 
  # nginx
  nginx:
      image: nginx:alpine3.18
      restart: unless-stopped
      ports:
          - "8080:80"
      volumes:
          - ./:/var/www
          - ./docker/nginx/:/etc/nginx/conf.d/
      networks:
          - laravel-network

networks:
  laravel-network:
    driver: bridge
